# Generated by Django 3.2.9 on 2021-12-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.FileField(default='../media/app/course-default.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.FileField(default='../media/app/program-default.png', upload_to='media'),
        ),
    ]
