# Generated by Django 3.2.9 on 2021-12-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211210_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('desired_time', models.DateTimeField()),
                ('child_name', models.CharField(max_length=50)),
                ('child_dob', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=50)),
                ('number_of_people', models.IntegerField()),
                ('telephone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=255)),
                ('desired_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.FileField(default='../media/app/course-default.png', upload_to='app'),
        ),
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.FileField(default='../media/app/program-default.png', upload_to='app'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='schoolappointment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='schoolappointment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.program'),
        ),
        migrations.AddField(
            model_name='parentappointment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='parentappointment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.program'),
        ),
    ]
