# Generated by Django 3.2.9 on 2022-01-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211210_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
