# Generated by Django 3.2.9 on 2022-01-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enroll_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentappointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='parentappointment',
            name='last_name',
        ),
        migrations.AddField(
            model_name='parentappointment',
            name='intake',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parentappointment',
            name='parent_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentappointment',
            name='parent_name',
            field=models.CharField(default='parent', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolappointment',
            name='email',
            field=models.EmailField(default='parent@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolappointment',
            name='intake',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
